name: Happo Workflow
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
jobs:
  happo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npx --package=happo.io happo-ci-github-actions
        env:
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}